# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tagged_children',
            field=models.ManyToManyField(blank=True, related_name='photos', to='registration.Child', verbose_name='학생'),
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Curriculum', verbose_name='교과 과정'),
        ),
        migrations.AddField(
            model_name='course',
            name='linked_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='registration.Class', verbose_name='학급'),
        ),
        migrations.AddField(
            model_name='album',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Course', verbose_name='수업'),
        ),
        migrations.AddField(
            model_name='album',
            name='linked_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='registration.Class', verbose_name='반'),
        ),
    ]
