# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180104_1302'),
        ('data', '0002_auto_20171219_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='날짜')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('linked_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='registration.Class', verbose_name='반')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('linked_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registration.Class', verbose_name='반')),
            ],
        ),
    ]
