# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 08:33
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_announcement_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='photos', verbose_name='사진 경로'),
        ),
    ]
