# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180117_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(default='', verbose_name='내용'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_created=True, verbose_name='날짜'),
        ),
    ]
