# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 01:21
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180118_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='profile_photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='프로필 사진'),
        ),
    ]
